'use client';
import React from 'react';
import { Clock3,Save,ShieldCheck } from 'lucide-react';
import { useApp } from '@/lib/context/app-context';
import { getSupabaseBrowserClient } from '@/lib/supabase/client';
import { peoplePayQueries } from '@/lib/supabase/peoplepay360_supabase_queries';
import { readLocalData, writeLocalData } from '@/lib/demo/local-fallback';

export function OvertimePolicyView(){
  const {currentRole,showToast,companyId,authenticated}=useApp();const canEdit=currentRole==='hr_manager'||currentRole==='payroll_manager'||currentRole==='admin';
  const [saving,setSaving]=React.useState(false);const [policy,setPolicy]=React.useState(()=>readLocalData('overtime-policy',{enabled:true,payEnabled:true,minimumMinutes:30,maxDaily:4,maxMonthly:40,rounding:15,multiplier:1.5,base:'basic',fixedHourlyRate:250,requiresApproval:true,categories:['full_time'] as string[]}));
  const field='w-full mt-1 px-3 py-2 rounded-[9px] border border-[#E4E1E5] bg-white text-xs disabled:bg-[#F4F3F5]';
  const save=async()=>{if(!canEdit)return;setSaving(true);try{const client=getSupabaseBrowserClient(),resolvedCompanyId=companyId||process.env.NEXT_PUBLIC_DEMO_COMPANY_ID;if(policy.base==='fixed_hourly'&&policy.fixedHourlyRate<=0)throw new Error('Enter a fixed hourly rate for this calculation base.');if(!authenticated||!resolvedCompanyId){writeLocalData('overtime-policy',policy);showToast('success','Overtime policy saved locally');return;}if(!client)throw new Error('Supabase is unavailable.');const version=await peoplePayQueries.nextOvertimePolicyVersion(client,resolvedCompanyId);await peoplePayQueries.saveOvertimePolicy(client,{company_id:resolvedCompanyId,version,enabled:policy.enabled,pay_enabled:policy.payEnabled,minimum_eligible_minutes:policy.minimumMinutes,max_hours_per_day:policy.maxDaily,max_hours_per_month:policy.maxMonthly,rounding_interval_minutes:policy.rounding,multiplier:policy.multiplier,calculation_base:policy.base,fixed_hourly_rate:policy.base==='fixed_hourly'?policy.fixedHourlyRate:null,requires_manager_approval:policy.requiresApproval,eligible_employment_categories:policy.categories,effective_from:new Date().toISOString().slice(0,10)});writeLocalData('overtime-policy',policy);showToast('success',`Overtime policy version ${version} saved`);}catch(error){showToast('error',error instanceof Error?error.message:'Unable to save overtime policy')}finally{setSaving(false)}};
  return <div className="space-y-4"><div className="p-5 bg-white rounded-[16px] border border-[#E4E1E5] flex items-center justify-between"><div><h2 className="text-xl font-bold flex items-center gap-2"><Clock3 className="w-5 h-5 text-[#714B67]"/>Overtime Policy</h2><p className="text-xs text-[#74717A] mt-1">Versioned company payroll controls. Open attendance sessions are never eligible.</p></div><span className="text-[10px] font-bold text-[#714B67] bg-[#F3EEF2] px-2 py-1 rounded">{canEdit?'Editable':'Read only'}</span></div><div className="p-5 bg-white rounded-[16px] border border-[#E4E1E5] grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 text-xs">
    <label className="flex items-center gap-2"><input disabled={!canEdit} type="checkbox" checked={policy.enabled} onChange={e=>setPolicy({...policy,enabled:e.target.checked})}/>Overtime tracking enabled</label><label className="flex items-center gap-2"><input disabled={!canEdit} type="checkbox" checked={policy.payEnabled} onChange={e=>setPolicy({...policy,payEnabled:e.target.checked})}/>Overtime pay enabled</label><label className="flex items-center gap-2"><input disabled={!canEdit} type="checkbox" checked={policy.requiresApproval} onChange={e=>setPolicy({...policy,requiresApproval:e.target.checked})}/>Manager approval required</label>
    <label>Minimum eligible minutes<input disabled={!canEdit} className={field} type="number" min="0" value={policy.minimumMinutes} onChange={e=>setPolicy({...policy,minimumMinutes:+e.target.value})}/></label><label>Maximum hours/day<input disabled={!canEdit} className={field} type="number" min="0" step=".5" value={policy.maxDaily} onChange={e=>setPolicy({...policy,maxDaily:+e.target.value})}/></label><label>Maximum hours/month<input disabled={!canEdit} className={field} type="number" min="0" value={policy.maxMonthly} onChange={e=>setPolicy({...policy,maxMonthly:+e.target.value})}/></label><label>Rounding interval<input disabled={!canEdit} className={field} type="number" min="1" value={policy.rounding} onChange={e=>setPolicy({...policy,rounding:+e.target.value})}/></label><label>Multiplier<input disabled={!canEdit} className={field} type="number" min="0" step=".1" value={policy.multiplier} onChange={e=>setPolicy({...policy,multiplier:+e.target.value})}/></label><label>Calculation base<select disabled={!canEdit} className={field} value={policy.base} onChange={e=>setPolicy({...policy,base:e.target.value})}><option value="basic">Basic salary</option><option value="gross">Gross salary</option><option value="fixed_hourly">Fixed hourly rate</option></select></label>{policy.base==='fixed_hourly'&&<label>Fixed hourly rate<input disabled={!canEdit} className={field} type="number" min="0.01" step=".01" value={policy.fixedHourlyRate} onChange={e=>setPolicy({...policy,fixedHourlyRate:+e.target.value})}/></label>}
    <div className="sm:col-span-2 lg:col-span-3 p-3 rounded-[10px] bg-[#FBFAFB] border border-[#E4E1E5]"><strong>Eligible employment categories</strong><div className="flex flex-wrap gap-4 mt-2">{['full_time','part_time','contractor','intern','trainee'].map(category=><label key={category} className="flex items-center gap-1.5"><input disabled={!canEdit} type="checkbox" checked={policy.categories.includes(category)} onChange={e=>setPolicy({...policy,categories:e.target.checked?[...policy.categories,category]:policy.categories.filter(c=>c!==category)})}/>{category.replaceAll('_',' ')}</label>)}</div></div>
    <div className="sm:col-span-2 lg:col-span-3 p-3 rounded-[10px] bg-[#FFF6D2] border border-[#F8E29E] flex items-start gap-2"><ShieldCheck className="w-4 h-4 text-[#9A6B0A] mt-0.5"/><p><strong>Example:</strong> Approved OT 6 hours × ₹250 hourly rate × {policy.multiplier} = ₹{(6*250*policy.multiplier).toLocaleString('en-IN')}. When pay is off, approved hours remain reportable at ₹0.</p></div>
    {canEdit&&<div className="sm:col-span-2 lg:col-span-3 flex justify-end"><button disabled={saving} onClick={save} className="px-4 py-2 bg-[#714B67] text-white rounded-[10px] font-bold flex items-center gap-2 disabled:opacity-50"><Save className="w-4 h-4"/>{saving?'Saving…':'Save new policy version'}</button></div>}
  </div></div>
}
