import { AttendanceRecord } from '@/lib/types';

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  // Today: Sep 04, 2026
  {
    id: 'att-20260904-1',
    employeeId: 'emp-1',
    employeeName: 'Rohan Sharma',
    date: '2026-09-04',
    checkIn: '09:28 AM',
    checkOut: null,
    workedHours: 6.8,
    overtimeHours: 0,
    status: 'present',
    verificationMethod: 'face',
    exceptionStatus: 'normal',
    notes: 'Verified via Mobile Face Biometrics',
  },
  {
    id: 'att-20260903-1',
    employeeId: 'emp-1',
    employeeName: 'Rohan Sharma',
    date: '2026-09-03',
    checkIn: '09:31 AM',
    checkOut: '06:45 PM',
    workedHours: 8.2,
    overtimeHours: 0.2,
    status: 'present',
    verificationMethod: 'face',
    exceptionStatus: 'normal',
  },
  {
    id: 'att-20260902-1',
    employeeId: 'emp-1',
    employeeName: 'Rohan Sharma',
    date: '2026-09-02',
    checkIn: '09:24 AM',
    checkOut: '07:15 PM',
    workedHours: 8.8,
    overtimeHours: 0.8,
    overtimePaymentStatus: 'paid',
    status: 'present',
    verificationMethod: 'biometric',
    exceptionStatus: 'normal',
  },
  {
    id: 'att-20260901-1',
    employeeId: 'emp-1',
    employeeName: 'Rohan Sharma',
    date: '2026-09-01',
    checkIn: '09:35 AM',
    checkOut: '06:30 PM',
    workedHours: 8.0,
    overtimeHours: 0,
    status: 'present',
    verificationMethod: 'face',
    exceptionStatus: 'normal',
  },
  // August days
  {
    id: 'att-20260831-1',
    employeeId: 'emp-1',
    employeeName: 'Rohan Sharma',
    date: '2026-08-31',
    checkIn: '09:29 AM',
    checkOut: '06:32 PM',
    workedHours: 8.0,
    overtimeHours: 0,
    status: 'present',
    verificationMethod: 'biometric',
    exceptionStatus: 'normal',
  },
  {
    id: 'att-20260828-1',
    employeeId: 'emp-1',
    employeeName: 'Rohan Sharma',
    date: '2026-08-28',
    checkIn: '09:18 AM',
    checkOut: '07:30 PM',
    workedHours: 9.2,
    overtimeHours: 1.2,
    status: 'present',
    verificationMethod: 'face',
    exceptionStatus: 'normal',
  },
  {
    id: 'att-20260827-1',
    employeeId: 'emp-1',
    employeeName: 'Rohan Sharma',
    date: '2026-08-27',
    checkIn: '10:15 AM',
    checkOut: '06:30 PM',
    workedHours: 7.2,
    overtimeHours: 0,
    status: 'late',
    verificationMethod: 'manual',
    exceptionStatus: 'late_arrival',
    notes: 'Traffic congestion on Hebbal flyover - Supervisor verified',
  },
  {
    id: 'att-20260826-1',
    employeeId: 'emp-1',
    employeeName: 'Rohan Sharma',
    date: '2026-08-26',
    checkIn: '09:25 AM',
    checkOut: '06:35 PM',
    workedHours: 8.1,
    overtimeHours: 0.1,
    status: 'present',
    verificationMethod: 'face',
    exceptionStatus: 'normal',
  },
  {
    id: 'att-20260825-1',
    employeeId: 'emp-1',
    employeeName: 'Rohan Sharma',
    date: '2026-08-25',
    checkIn: '09:30 AM',
    checkOut: '06:40 PM',
    workedHours: 8.1,
    overtimeHours: 0.1,
    status: 'present',
    verificationMethod: 'face',
    exceptionStatus: 'normal',
  },
  // Unpaid Leave days in August
  {
    id: 'att-20260812-1',
    employeeId: 'emp-1',
    employeeName: 'Rohan Sharma',
    date: '2026-08-12',
    checkIn: null,
    checkOut: null,
    workedHours: 0,
    overtimeHours: 0,
    status: 'leave',
    verificationMethod: 'manual',
    exceptionStatus: 'normal',
    notes: 'Approved Unpaid Leave (Loss of Pay)',
  },
  {
    id: 'att-20260811-1',
    employeeId: 'emp-1',
    employeeName: 'Rohan Sharma',
    date: '2026-08-11',
    checkIn: null,
    checkOut: null,
    workedHours: 0,
    overtimeHours: 0,
    status: 'leave',
    verificationMethod: 'manual',
    exceptionStatus: 'normal',
    notes: 'Approved Unpaid Leave (Loss of Pay)',
  },
  // Recorded overtime with pay disabled for the employee category.
  {
    id: 'att-20260903-6',
    employeeId: 'emp-6',
    employeeName: 'Kavita Menon',
    date: '2026-09-03',
    checkIn: '09:14 AM',
    checkOut: '07:20 PM',
    workedHours: 9.1,
    overtimeHours: 1.1,
    overtimePaymentStatus: 'recorded_unpaid',
    status: 'present',
    verificationMethod: 'face',
    exceptionStatus: 'normal',
    locationVerification: 'verified',
    latitude: 12.97161,
    longitude: 77.59458,
    accuracyMeters: 18,
    distanceFromOfficeMeters: 3,
    notes: 'Overtime retained for reporting; overtime pay is disabled for this employee category.',
  },
  // Outside-geofence attendance waiting for HR review.
  {
    id: 'att-20260904-8',
    employeeId: 'emp-8',
    employeeName: 'Arjun Verma',
    date: '2026-09-04',
    checkIn: '09:42 AM',
    checkOut: '06:36 PM',
    workedHours: 7.9,
    overtimeHours: 0,
    status: 'present',
    verificationMethod: 'face',
    exceptionStatus: 'pending_correction',
    locationVerification: 'outside_allowed_location',
    latitude: 12.9819,
    longitude: 77.6048,
    accuracyMeters: 22,
    distanceFromOfficeMeters: 1560,
    notes: 'Outside the Bengaluru HQ geofence; queued for HR location review.',
  },
  // Other employees records with some exceptions
  {
    id: 'att-20260904-7',
    employeeId: 'emp-7',
    employeeName: 'Aarav Mukherjee',
    date: '2026-09-04',
    checkIn: null,
    checkOut: null,
    workedHours: 0,
    overtimeHours: 0,
    status: 'absent',
    verificationMethod: 'manual',
    exceptionStatus: 'unauthorized_absence',
    notes: 'No check-in detected by 11:30 AM',
  },
  {
    id: 'att-20260904-9',
    employeeId: 'emp-9',
    employeeName: 'Sneha Iyer',
    date: '2026-09-04',
    checkIn: '10:14 AM',
    checkOut: null,
    workedHours: 5.5,
    overtimeHours: 0,
    status: 'late',
    verificationMethod: 'biometric',
    exceptionStatus: 'late_arrival',
    notes: 'Arrived 44 mins past grace period',
  },
  {
    id: 'att-20260903-10',
    employeeId: 'emp-10',
    employeeName: 'Deepak Chawla',
    date: '2026-09-03',
    checkIn: '09:20 AM',
    checkOut: null,
    workedHours: 8.0,
    overtimeHours: 0,
    status: 'present',
    verificationMethod: 'face',
    exceptionStatus: 'missing_checkout',
    notes: 'System auto-closed without employee signout',
  },
];
