import { Contract } from '@/lib/types';

export const CONTRACTS: Contract[] = [
  {
    id: 'cnt-1',
    employeeId: 'emp-1',
    employeeName: 'Rohan Sharma',
    contractReference: 'CNT-2024-ENG-042',
    wage: 43500,
    startDate: '2024-04-01',
    endDate: '2027-03-31',
    department: 'Engineering',
    jobPosition: 'Senior Software Engineer',
    salaryStructureId: 'str-2',
    salaryStructureName: 'Tech Engineering Salary Structure',
    status: 'running',
    isActive: true,
  },
  {
    id: 'cnt-2',
    employeeId: 'emp-2',
    employeeName: 'Priya Sundaram',
    contractReference: 'CNT-2023-HR-008',
    wage: 75000,
    startDate: '2023-08-01',
    endDate: '2026-07-31',
    department: 'Human Resources',
    jobPosition: 'People Operations Manager',
    salaryStructureId: 'str-1',
    salaryStructureName: 'Standard Corporate Salary Structure',
    status: 'expired',
    isActive: false,
  },
  {
    id: 'cnt-3',
    employeeId: 'emp-3',
    employeeName: 'Neha Gupta',
    contractReference: 'CNT-2023-FIN-015',
    wage: 58000,
    startDate: '2023-02-10',
    endDate: '2026-02-09',
    department: 'Finance & Payroll',
    jobPosition: 'Senior Payroll Specialist',
    salaryStructureId: 'str-1',
    salaryStructureName: 'Standard Corporate Salary Structure',
    status: 'expired',
    isActive: false,
  },
  {
    id: 'cnt-4',
    employeeId: 'emp-4',
    employeeName: 'Rajesh Kulkarni',
    contractReference: 'CNT-2022-FIN-001',
    wage: 115000,
    startDate: '2022-01-15',
    endDate: '2027-01-14',
    department: 'Finance & Payroll',
    jobPosition: 'Payroll Operations Director',
    salaryStructureId: 'str-3',
    salaryStructureName: 'Executive Leadership Salary Structure',
    status: 'running',
    isActive: true,
  },
  {
    id: 'cnt-5',
    employeeId: 'emp-5',
    employeeName: 'Sudeesh K',
    contractReference: 'CNT-2021-ADM-001',
    wage: 145000,
    startDate: '2021-03-01',
    endDate: '2028-02-29',
    department: 'Operations',
    jobPosition: 'Global HR Operations Administrator',
    salaryStructureId: 'str-3',
    salaryStructureName: 'Executive Leadership Salary Structure',
    status: 'running',
    isActive: true,
  },
  {
    id: 'cnt-6',
    employeeId: 'emp-6',
    employeeName: 'Kavita Menon',
    contractReference: 'CNT-2023-PRD-020',
    wage: 64000,
    startDate: '2023-06-20',
    endDate: '2026-06-19',
    department: 'Product & Design',
    jobPosition: 'Lead Product Designer',
    salaryStructureId: 'str-2',
    salaryStructureName: 'Tech Engineering Salary Structure',
    status: 'expired',
    isActive: false,
  },
  {
    id: 'cnt-7',
    employeeId: 'emp-7',
    employeeName: 'Aarav Mukherjee',
    contractReference: 'CNT-2024-ENG-088',
    wage: 47000,
    startDate: '2024-01-10',
    endDate: '2027-01-09',
    department: 'Engineering',
    jobPosition: 'Full Stack Engineer',
    salaryStructureId: 'str-2',
    salaryStructureName: 'Tech Engineering Salary Structure',
    status: 'running',
    isActive: true,
  },
  {
    id: 'cnt-11',
    employeeId: 'emp-11',
    employeeName: 'Meera Nambiar',
    contractReference: 'CNT-2024-HR-044',
    wage: 37000,
    startDate: '2024-08-10',
    endDate: '2025-08-09',
    department: 'Human Resources',
    jobPosition: 'Talent Acquisition Partner',
    salaryStructureId: 'str-1',
    salaryStructureName: 'Standard Corporate Salary Structure',
    status: 'expired',
    isActive: false,
    warnings: ['Missing bank details for electronic NEFT transfer'],
  },
  {
    id: 'cnt-12', employeeId: 'emp-2', employeeName: 'Priya Sundaram', contractReference: 'CNT-2026-HR-009', wage: 82000, startDate: '2026-10-01', endDate: '2027-09-30', department: 'Human Resources', jobPosition: 'People Operations Manager', salaryStructureId: 'str-1', salaryStructureName: 'Standard Corporate Salary Structure', status: 'scheduled', isActive: false, approvedAt: '2026-08-20', workingScheduleId:'ws-1', workingScheduleName:'Standard Corporate Shift (9:30 AM - 6:30 PM)'
  },
  {
    id: 'cnt-13', employeeId: 'emp-6', employeeName: 'Kavita Menon', contractReference: 'DRAFT-2026-PRD-021', wage: 70000, startDate: '2026-10-01', endDate: '2027-09-30', department: 'Product & Design', jobPosition: 'Lead Product Designer', salaryStructureId: 'str-2', salaryStructureName: 'Tech Engineering Salary Structure', status: 'draft', isActive: false, renewalMode: 'automatic', renewalTermMonths: 12, renewalOfContractId: 'cnt-6', renewalDueDate: '2026-09-20', warningType: 'expiring_soon', warningDetails: 'Auto-renewal draft generated from CNT-2023-PRD-020. HR approval will schedule the renewed term.'
  },
  {
    id: 'cnt-14', employeeId: 'emp-11', employeeName: 'Meera Nambiar', contractReference: 'DRAFT-2026-HR-045', wage: 41000, startDate: '2026-10-15', endDate: '2027-10-14', department: 'Human Resources', jobPosition: 'Talent Acquisition Partner', salaryStructureId: 'str-1', salaryStructureName: 'Standard Corporate Salary Structure', status: 'draft', isActive: false, renewalMode: 'manual', renewalTermMonths: 12, renewalOfContractId: 'cnt-11', renewalDueDate: '2026-09-30', warningDetails: 'Renewal draft requires bank-detail verification before approval.'
  },
];
