import { Department, WorkingSchedule } from '@/lib/types';

export const DEPARTMENTS: Department[] = [
  {
    id: 'dept-1',
    name: 'Engineering',
    code: 'ENG',
    managerId: 'emp-2',
    managerName: 'Priya Sundaram',
    totalHeadcount: 42,
    monthlyPayrollBudget: 3850000,
  },
  {
    id: 'dept-2',
    name: 'Human Resources',
    code: 'HR',
    managerId: 'emp-2',
    managerName: 'Priya Sundaram',
    totalHeadcount: 12,
    monthlyPayrollBudget: 980000,
  },
  {
    id: 'dept-3',
    name: 'Finance & Payroll',
    code: 'FIN',
    managerId: 'emp-4',
    managerName: 'Rajesh Kulkarni',
    totalHeadcount: 16,
    monthlyPayrollBudget: 1450000,
  },
  {
    id: 'dept-4',
    name: 'Product & Design',
    code: 'PRD',
    managerId: 'emp-6',
    managerName: 'Kavita Menon',
    totalHeadcount: 18,
    monthlyPayrollBudget: 1620000,
  },
  {
    id: 'dept-5',
    name: 'Sales & Marketing',
    code: 'SLS',
    managerId: 'emp-8',
    managerName: 'Arjun Verma',
    totalHeadcount: 24,
    monthlyPayrollBudget: 1980000,
  },
  {
    id: 'dept-6',
    name: 'Operations',
    code: 'OPS',
    managerId: 'emp-5',
    managerName: 'Sudeesh K',
    totalHeadcount: 20,
    monthlyPayrollBudget: 1350000,
  },
];

export const WORKING_SCHEDULES: WorkingSchedule[] = [
  {
    id: 'ws-1',
    name: 'Standard Corporate Shift (9:30 AM - 6:30 PM)',
    type: 'standard',
    weeklyHours: 40,
    days: [
      { day: 'Monday', dayShort: 'Mon', startTime: '09:30', endTime: '18:30', breakDurationMins: 60, isWorking: true },
      { day: 'Tuesday', dayShort: 'Tue', startTime: '09:30', endTime: '18:30', breakDurationMins: 60, isWorking: true },
      { day: 'Wednesday', dayShort: 'Wed', startTime: '09:30', endTime: '18:30', breakDurationMins: 60, isWorking: true },
      { day: 'Thursday', dayShort: 'Thu', startTime: '09:30', endTime: '18:30', breakDurationMins: 60, isWorking: true },
      { day: 'Friday', dayShort: 'Fri', startTime: '09:30', endTime: '18:30', breakDurationMins: 60, isWorking: true },
      { day: 'Saturday', dayShort: 'Sat', startTime: '10:00', endTime: '14:00', breakDurationMins: 0, isWorking: false },
      { day: 'Sunday', dayShort: 'Sun', startTime: '00:00', endTime: '00:00', breakDurationMins: 0, isWorking: false },
    ],
  },
  {
    id: 'ws-2',
    name: 'Flexible Tech Schedule (8 Hours/Day Core 11:00-16:00)',
    type: 'flexible',
    weeklyHours: 40,
    days: [
      { day: 'Monday', dayShort: 'Mon', startTime: '10:00', endTime: '19:00', breakDurationMins: 60, isWorking: true },
      { day: 'Tuesday', dayShort: 'Tue', startTime: '10:00', endTime: '19:00', breakDurationMins: 60, isWorking: true },
      { day: 'Wednesday', dayShort: 'Wed', startTime: '10:00', endTime: '19:00', breakDurationMins: 60, isWorking: true },
      { day: 'Thursday', dayShort: 'Thu', startTime: '10:00', endTime: '19:00', breakDurationMins: 60, isWorking: true },
      { day: 'Friday', dayShort: 'Fri', startTime: '10:00', endTime: '19:00', breakDurationMins: 60, isWorking: true },
      { day: 'Saturday', dayShort: 'Sat', startTime: '00:00', endTime: '00:00', breakDurationMins: 0, isWorking: false },
      { day: 'Sunday', dayShort: 'Sun', startTime: '00:00', endTime: '00:00', breakDurationMins: 0, isWorking: false },
    ],
  },
  {
    id: 'ws-3',
    name: 'Operations Early Shift (8:00 AM - 4:30 PM)',
    type: 'shift',
    weeklyHours: 40,
    days: [
      { day: 'Monday', dayShort: 'Mon', startTime: '08:00', endTime: '16:30', breakDurationMins: 30, isWorking: true },
      { day: 'Tuesday', dayShort: 'Tue', startTime: '08:00', endTime: '16:30', breakDurationMins: 30, isWorking: true },
      { day: 'Wednesday', dayShort: 'Wed', startTime: '08:00', endTime: '16:30', breakDurationMins: 30, isWorking: true },
      { day: 'Thursday', dayShort: 'Thu', startTime: '08:00', endTime: '16:30', breakDurationMins: 30, isWorking: true },
      { day: 'Friday', dayShort: 'Fri', startTime: '08:00', endTime: '16:30', breakDurationMins: 30, isWorking: true },
      { day: 'Saturday', dayShort: 'Sat', startTime: '08:00', endTime: '13:00', breakDurationMins: 0, isWorking: false },
      { day: 'Sunday', dayShort: 'Sun', startTime: '00:00', endTime: '00:00', breakDurationMins: 0, isWorking: false },
    ],
  },
  {
    id: 'ws-45',
    name: 'Extended 45 Hour Schedule (9:00 AM - 7:00 PM)',
    type: 'standard',
    weeklyHours: 45,
    days: [
      { day: 'Monday', dayShort: 'Mon', startTime: '09:00', endTime: '19:00', breakDurationMins: 60, isWorking: true },
      { day: 'Tuesday', dayShort: 'Tue', startTime: '09:00', endTime: '19:00', breakDurationMins: 60, isWorking: true },
      { day: 'Wednesday', dayShort: 'Wed', startTime: '09:00', endTime: '19:00', breakDurationMins: 60, isWorking: true },
      { day: 'Thursday', dayShort: 'Thu', startTime: '09:00', endTime: '19:00', breakDurationMins: 60, isWorking: true },
      { day: 'Friday', dayShort: 'Fri', startTime: '09:00', endTime: '19:00', breakDurationMins: 60, isWorking: true },
      { day: 'Saturday', dayShort: 'Sat', startTime: '00:00', endTime: '00:00', breakDurationMins: 0, isWorking: false },
      { day: 'Sunday', dayShort: 'Sun', startTime: '00:00', endTime: '00:00', breakDurationMins: 0, isWorking: false },
    ],
  },
];
