import { Employee } from '@/lib/types';

export const EMPLOYEES: Employee[] = [
  {
    id: 'emp-1',
    employeeId: 'PP-EMP-1042',
    name: 'Rohan Sharma',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    email: 'rohan.sharma@peoplepay360.internal',
    phone: '+91 98201 44521',
    personalEmail: 'rohan.tech.sharma@gmail.com',
    address: 'B-402, Green Meadows, Outer Ring Road, Bengaluru, Karnataka 560103',
    jobPosition: 'Senior Software Engineer',
    departmentId: 'dept-1',
    departmentName: 'Engineering',
    reportingManagerId: 'emp-2',
    reportingManagerName: 'Priya Sundaram',
    joiningDate: '2022-04-15',
    employmentStatus: 'active',
    employeeType: 'full_time',
    currentAttendanceStatus: 'checked_in',
    todayCheckInTime: '09:28 AM',
    todayCheckOutTime: null,
    bankAccountMasked: 'HDFC •••• •••• 8412',
    ifscCode: 'HDFC0001245',
    panNumber: 'ABCPS4521K',
    emergencyContact: {
      name: 'Sunita Sharma',
      relation: 'Spouse',
      phone: '+91 98201 88942',
    },
    activeContractId: 'cnt-1',
    workingScheduleId: 'ws-1',
    workingScheduleName: 'Standard Corporate Shift (9:30 AM - 6:30 PM)',
    paidLeaveBalance: 8,
    unpaidLeaveTaken: 2,
    pendingRequestsCount: 1,
    attendanceException: false,
    baseSalary: 35000,
  },
  {
    id: 'emp-2',
    employeeId: 'PP-HR-2008',
    name: 'Priya Sundaram',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    email: 'priya.sundaram@peoplepay360.internal',
    phone: '+91 99402 11984',
    personalEmail: 'priya.sundaram@outlook.com',
    address: 'Flat 12A, Coral Heights, Indiranagar, Bengaluru, Karnataka 560038',
    jobPosition: 'People Operations Manager',
    departmentId: 'dept-2',
    departmentName: 'Human Resources',
    reportingManagerId: 'emp-5',
    reportingManagerName: 'Sudeesh K',
    joiningDate: '2020-08-01',
    employmentStatus: 'active',
    employeeType: 'full_time',
    currentAttendanceStatus: 'checked_in',
    todayCheckInTime: '09:15 AM',
    todayCheckOutTime: null,
    bankAccountMasked: 'ICIC •••• •••• 3901',
    ifscCode: 'ICIC0000047',
    panNumber: 'BKLPS9910D',
    emergencyContact: {
      name: 'Venkatesh Sundaram',
      relation: 'Father',
      phone: '+91 98400 32115',
    },
    activeContractId: 'cnt-2',
    workingScheduleId: 'ws-1',
    workingScheduleName: 'Standard Corporate Shift (9:30 AM - 6:30 PM)',
    paidLeaveBalance: 14,
    unpaidLeaveTaken: 0,
    pendingRequestsCount: 0,
    attendanceException: false,
    baseSalary: 62000,
  },
  {
    id: 'emp-3',
    employeeId: 'PP-PAY-3015',
    name: 'Neha Gupta',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    email: 'neha.gupta@peoplepay360.internal',
    phone: '+91 97113 55290',
    personalEmail: 'v.malhotra.fin@gmail.com',
    address: 'Villa 18, Palm Meadows, Whitefield, Bengaluru 560066',
    jobPosition: 'Senior Payroll Specialist',
    departmentId: 'dept-3',
    departmentName: 'Finance & Payroll',
    reportingManagerId: 'emp-4',
    reportingManagerName: 'Rajesh Kulkarni',
    joiningDate: '2021-02-10',
    employmentStatus: 'active',
    employeeType: 'full_time',
    currentAttendanceStatus: 'checked_in',
    todayCheckInTime: '09:32 AM',
    todayCheckOutTime: null,
    bankAccountMasked: 'SBIN •••• •••• 9924',
    ifscCode: 'SBIN0004120',
    panNumber: 'CDEPM7721P',
    emergencyContact: {
      name: 'Anita Malhotra',
      relation: 'Spouse',
      phone: '+91 98114 66321',
    },
    activeContractId: 'cnt-3',
    workingScheduleId: 'ws-1',
    workingScheduleName: 'Standard Corporate Shift (9:30 AM - 6:30 PM)',
    paidLeaveBalance: 11,
    unpaidLeaveTaken: 1,
    pendingRequestsCount: 0,
    attendanceException: false,
    baseSalary: 48000,
  },
  {
    id: 'emp-4',
    employeeId: 'PP-PAY-3001',
    name: 'Rajesh Kulkarni',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    email: 'rajesh.kulkarni@peoplepay360.internal',
    phone: '+91 98230 44910',
    personalEmail: 'ananya.deshmukh@yahoo.com',
    address: 'Penthouse 4, Skyline Towers, Koramangala 4th Block, Bengaluru 560034',
    jobPosition: 'Payroll Operations Director',
    departmentId: 'dept-3',
    departmentName: 'Finance & Payroll',
    reportingManagerId: 'emp-5',
    reportingManagerName: 'Sudeesh K',
    joiningDate: '2019-01-15',
    employmentStatus: 'active',
    employeeType: 'full_time',
    currentAttendanceStatus: 'checked_in',
    todayCheckInTime: '09:05 AM',
    todayCheckOutTime: null,
    bankAccountMasked: 'KKBK •••• •••• 1209',
    ifscCode: 'KKBK0000192',
    panNumber: 'DFGPD1120M',
    emergencyContact: {
      name: 'Nitin Deshmukh',
      relation: 'Brother',
      phone: '+91 98230 99401',
    },
    activeContractId: 'cnt-4',
    workingScheduleId: 'ws-1',
    workingScheduleName: 'Standard Corporate Shift (9:30 AM - 6:30 PM)',
    paidLeaveBalance: 18,
    unpaidLeaveTaken: 0,
    pendingRequestsCount: 0,
    attendanceException: false,
    baseSalary: 95000,
  },
  {
    id: 'emp-5',
    employeeId: 'PP-ADM-1001',
    name: 'Sudeesh K',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    email: 'sudeesh.k@peoplepay360.internal',
    phone: '+91 98795 22001',
    personalEmail: 'sudeesh.k@gmail.com',
    address: '702, Prestige Hermitage, Kensington Road, Bengaluru 560042',
    jobPosition: 'Global HR Operations Administrator',
    departmentId: 'dept-6',
    departmentName: 'Operations',
    reportingManagerId: 'emp-5',
    reportingManagerName: 'Board of Directors',
    joiningDate: '2018-03-01',
    employmentStatus: 'active',
    employeeType: 'full_time',
    currentAttendanceStatus: 'checked_in',
    todayCheckInTime: '08:50 AM',
    todayCheckOutTime: null,
    bankAccountMasked: 'HDFC •••• •••• 4400',
    ifscCode: 'HDFC0000084',
    panNumber: 'EGHPP8841Z',
    emergencyContact: {
      name: 'Meena Patel',
      relation: 'Spouse',
      phone: '+91 98795 33412',
    },
    activeContractId: 'cnt-5',
    workingScheduleId: 'ws-1',
    workingScheduleName: 'Standard Corporate Shift (9:30 AM - 6:30 PM)',
    paidLeaveBalance: 20,
    unpaidLeaveTaken: 0,
    pendingRequestsCount: 0,
    attendanceException: false,
    baseSalary: 120000,
  },
  {
    id: 'emp-6',
    employeeId: 'PP-EMP-1088',
    name: 'Kavita Menon',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    email: 'kavita.menon@peoplepay360.internal',
    phone: '+91 98450 67123',
    personalEmail: 'kavita.menon.design@gmail.com',
    address: '34, Lavelle Road, Shanthala Nagar, Bengaluru 560001',
    jobPosition: 'Lead Product Designer',
    departmentId: 'dept-4',
    departmentName: 'Product & Design',
    reportingManagerId: 'emp-2',
    reportingManagerName: 'Priya Sundaram',
    joiningDate: '2021-06-20',
    employmentStatus: 'active',
    employeeType: 'full_time',
    currentAttendanceStatus: 'checked_in',
    todayCheckInTime: '09:40 AM',
    todayCheckOutTime: null,
    bankAccountMasked: 'AXIS •••• •••• 7731',
    ifscCode: 'UTIB0000010',
    panNumber: 'JKLPM3310N',
    emergencyContact: {
      name: 'Ramesh Menon',
      relation: 'Spouse',
      phone: '+91 98450 99812',
    },
    activeContractId: 'cnt-6',
    workingScheduleId: 'ws-2',
    workingScheduleName: 'Flexible Tech Schedule (8 Hours/Day Core 11:00-16:00)',
    paidLeaveBalance: 6,
    unpaidLeaveTaken: 1,
    pendingRequestsCount: 1,
    attendanceException: false,
    baseSalary: 52000,
  },
  {
    id: 'emp-7',
    employeeId: 'PP-EMP-1102',
    name: 'Aarav Mukherjee',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    email: 'aarav.mukherjee@peoplepay360.internal',
    phone: '+91 98300 78234',
    personalEmail: 'aarav.dev.mukherjee@gmail.com',
    address: 'Flat 301, Silver Springs, HSR Layout Sector 2, Bengaluru 560102',
    jobPosition: 'Full Stack Engineer',
    departmentId: 'dept-1',
    departmentName: 'Engineering',
    reportingManagerId: 'emp-1',
    reportingManagerName: 'Rohan Sharma',
    joiningDate: '2023-01-10',
    employmentStatus: 'active',
    employeeType: 'full_time',
    currentAttendanceStatus: 'checked_out',
    todayCheckInTime: null,
    todayCheckOutTime: null,
    bankAccountMasked: 'HDFC •••• •••• 2154',
    ifscCode: 'HDFC0001245',
    panNumber: 'MNPPA9921Q',
    emergencyContact: {
      name: 'Debashis Mukherjee',
      relation: 'Father',
      phone: '+91 98300 11209',
    },
    activeContractId: 'cnt-7',
    workingScheduleId: 'ws-1',
    workingScheduleName: 'Standard Corporate Shift (9:30 AM - 6:30 PM)',
    paidLeaveBalance: 9,
    unpaidLeaveTaken: 0,
    pendingRequestsCount: 0,
    attendanceException: true, // Missing check-in flag
    baseSalary: 38000,
  },
  {
    id: 'emp-8',
    employeeId: 'PP-EMP-1145',
    name: 'Arjun Verma',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    email: 'arjun.verma@peoplepay360.internal',
    phone: '+91 98100 45890',
    personalEmail: 'arjun.growth.verma@gmail.com',
    address: 'C-12, Diamond District, Old Airport Road, Bengaluru 560008',
    jobPosition: 'Enterprise Account Director',
    departmentId: 'dept-5',
    departmentName: 'Sales & Marketing',
    reportingManagerId: 'emp-5',
    reportingManagerName: 'Sudeesh K',
    joiningDate: '2021-11-15',
    employmentStatus: 'active',
    employeeType: 'full_time',
    currentAttendanceStatus: 'on_leave',
    todayCheckInTime: null,
    todayCheckOutTime: null,
    bankAccountMasked: 'ICIC •••• •••• 6610',
    ifscCode: 'ICIC0000047',
    panNumber: 'PRSVA4412R',
    emergencyContact: {
      name: 'Pooja Verma',
      relation: 'Spouse',
      phone: '+91 98100 88231',
    },
    activeContractId: 'cnt-8',
    workingScheduleId: 'ws-1',
    workingScheduleName: 'Standard Corporate Shift (9:30 AM - 6:30 PM)',
    paidLeaveBalance: 4,
    unpaidLeaveTaken: 0,
    pendingRequestsCount: 0,
    attendanceException: false,
    baseSalary: 75000,
  },
  {
    id: 'emp-9',
    employeeId: 'PP-EMP-1210',
    name: 'Sneha Iyer',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80',
    email: 'sneha.iyer@peoplepay360.internal',
    phone: '+91 99001 88234',
    personalEmail: 'sneha.iyer.qa@gmail.com',
    address: '104, Sobha Tulip, JP Nagar 6th Phase, Bengaluru 560078',
    jobPosition: 'Senior QA Automation Engineer',
    departmentId: 'dept-1',
    departmentName: 'Engineering',
    reportingManagerId: 'emp-1',
    reportingManagerName: 'Rohan Sharma',
    joiningDate: '2022-09-01',
    employmentStatus: 'active',
    employeeType: 'full_time',
    currentAttendanceStatus: 'checked_in',
    todayCheckInTime: '10:14 AM', // Late arrival exception
    todayCheckOutTime: null,
    bankAccountMasked: 'HDFC •••• •••• 5590',
    ifscCode: 'HDFC0001245',
    panNumber: 'QWERY1284T',
    emergencyContact: {
      name: 'Kalyan Iyer',
      relation: 'Brother',
      phone: '+91 99001 33412',
    },
    activeContractId: 'cnt-9',
    workingScheduleId: 'ws-1',
    workingScheduleName: 'Standard Corporate Shift (9:30 AM - 6:30 PM)',
    paidLeaveBalance: 7,
    unpaidLeaveTaken: 0,
    pendingRequestsCount: 1,
    attendanceException: true, // Late arrival
    baseSalary: 32000,
  },
  {
    id: 'emp-10',
    employeeId: 'PP-EMP-1290',
    name: 'Deepak Chawla',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    email: 'deepak.chawla@peoplepay360.internal',
    phone: '+91 98118 77621',
    personalEmail: 'deepak.c.ops@gmail.com',
    address: 'Flat 502, Embassy Habitat, Vasanth Nagar, Bengaluru 560052',
    jobPosition: 'DevOps & Cloud Engineer',
    departmentId: 'dept-1',
    departmentName: 'Engineering',
    reportingManagerId: 'emp-1',
    reportingManagerName: 'Rohan Sharma',
    joiningDate: '2023-05-18',
    employmentStatus: 'active',
    employeeType: 'full_time',
    currentAttendanceStatus: 'checked_in',
    todayCheckInTime: '09:25 AM',
    todayCheckOutTime: null,
    bankAccountMasked: 'SBIN •••• •••• 1108',
    ifscCode: 'SBIN0004120',
    panNumber: 'ZXCVD9912W',
    emergencyContact: {
      name: 'Sunil Chawla',
      relation: 'Father',
      phone: '+91 98118 22345',
    },
    activeContractId: 'cnt-10',
    workingScheduleId: 'ws-1',
    workingScheduleName: 'Standard Corporate Shift (9:30 AM - 6:30 PM)',
    paidLeaveBalance: 12,
    unpaidLeaveTaken: 0,
    pendingRequestsCount: 0,
    attendanceException: false,
    baseSalary: 42000,
  },
  {
    id: 'emp-11',
    employeeId: 'PP-EMP-1304',
    name: 'Meera Nambiar',
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80',
    email: 'meera.nambiar@peoplepay360.internal',
    phone: '+91 98470 33412',
    personalEmail: 'meera.hr.nambiar@gmail.com',
    address: 'B-201, Brigade Millennium, JP Nagar 7th Phase, Bengaluru 560078',
    jobPosition: 'Talent Acquisition Partner',
    departmentId: 'dept-2',
    departmentName: 'Human Resources',
    reportingManagerId: 'emp-2',
    reportingManagerName: 'Priya Sundaram',
    joiningDate: '2023-08-10',
    employmentStatus: 'active',
    employeeType: 'full_time',
    currentAttendanceStatus: 'checked_in',
    todayCheckInTime: '09:30 AM',
    todayCheckOutTime: null,
    bankAccountMasked: '', // Warning: Missing bank details!
    ifscCode: '',
    panNumber: 'LKJHG5512B',
    emergencyContact: {
      name: 'Gopal Nambiar',
      relation: 'Father',
      phone: '+91 98470 11982',
    },
    activeContractId: 'cnt-11',
    workingScheduleId: 'ws-1',
    workingScheduleName: 'Standard Corporate Shift (9:30 AM - 6:30 PM)',
    paidLeaveBalance: 10,
    unpaidLeaveTaken: 0,
    pendingRequestsCount: 0,
    attendanceException: false,
    baseSalary: 30000,
  },
  {
    id: 'emp-12',
    employeeId: 'PP-EMP-1350',
    name: 'Karan Singhania',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    email: 'karan.singhania@peoplepay360.internal',
    phone: '+91 98210 99432',
    personalEmail: 'karan.fin.singh@gmail.com',
    address: 'Villa 44, Adarsh Palm Retreat, Bellandur, Bengaluru 560103',
    jobPosition: 'Finance Intern',
    departmentId: 'dept-3',
    departmentName: 'Finance & Payroll',
    reportingManagerId: 'emp-3',
    reportingManagerName: 'Neha Gupta',
    joiningDate: '2024-02-01',
    employmentStatus: 'probation',
    employeeType: 'intern',
    currentAttendanceStatus: 'checked_in',
    todayCheckInTime: '09:18 AM',
    todayCheckOutTime: null,
    bankAccountMasked: 'HDFC •••• •••• 9940',
    ifscCode: 'HDFC0001245',
    panNumber: 'POIUY8823X',
    emergencyContact: {
      name: 'Renu Singhania',
      relation: 'Mother',
      phone: '+91 98210 11094',
    },
    activeContractId: 'cnt-12',
    workingScheduleId: 'ws-1',
    workingScheduleName: 'Standard Corporate Shift (9:30 AM - 6:30 PM)',
    paidLeaveBalance: 5,
    unpaidLeaveTaken: 0,
    pendingRequestsCount: 0,
    attendanceException: false,
    baseSalary: 34000,
  },
];
