import { LeaveType, LeaveRequest } from '@/lib/types';

export const LEAVE_TYPES: LeaveType[] = [
  {
    id: 'lt-1',
    name: 'Casual Leave (CL)',
    code: 'CL',
    isPaid: true,
    defaultDaysPerYear: 12,
    totalDays: 12,
    remainingDays: 8,
    color: '#714B67',
    description: 'For unanticipated personal matters and short leaves.',
  },
  {
    id: 'lt-2',
    name: 'Privilege / Earned Leave (PL/EL)',
    code: 'PL',
    isPaid: true,
    defaultDaysPerYear: 15,
    totalDays: 15,
    remainingDays: 11,
    color: '#438A6B',
    description: 'Cumulative annual vacation leave planned in advance.',
  },
  {
    id: 'lt-3',
    name: 'Sick Leave (SL)',
    code: 'SL',
    isPaid: true,
    defaultDaysPerYear: 8,
    totalDays: 8,
    remainingDays: 6,
    color: '#D49525',
    description: 'Medical recuperation and health emergencies.',
  },
  {
    id: 'lt-4',
    name: 'Unpaid Leave (Loss of Pay / LOP)',
    code: 'LOP',
    isPaid: false,
    defaultDaysPerYear: 0,
    color: '#C85A54',
    description: 'Unlimited unpaid time off. Approved days are deducted from payroll.',
  },
  {
    id: 'lt-5',
    name: 'Maternity / Paternity Leave',
    code: 'MAT',
    isPaid: true,
    defaultDaysPerYear: 180,
    totalDays: 180,
    remainingDays: 180,
    color: '#A4879F',
    description: 'Statutory parental leave with full pay protection.',
  },
];

export const UPCOMING_HOLIDAYS = [
  { date: '2026-10-02', name: 'Gandhi Jayanti', day: 'Friday' },
  { date: '2026-10-20', name: 'Dussehra (Vijayadashami)', day: 'Tuesday' },
  { date: '2026-11-08', name: 'Diwali (Deepavali)', day: 'Sunday' },
  { date: '2026-12-25', name: 'Christmas Day', day: 'Friday' },
];

export const INITIAL_LEAVE_REQUESTS: LeaveRequest[] = [
  {
    id: 'lr-100',
    employeeId: 'emp-1',
    employeeName: 'Rohan Sharma',
    leaveTypeId: 'lt-1',
    leaveTypeName: 'Casual Leave (CL)',
    isPaid: true,
    startDate: '2026-07-17',
    endDate: '2026-07-17',
    isHalfDay: false,
    reason: 'Personal appointment during a production support rotation.',
    calendarDays: 1,
    excludedWeekends: 0,
    excludedHolidays: 0,
    chargeableWorkingDays: 1,
    paidDaysUsed: 0,
    unpaidDays: 0,
    estimatedDeduction: 0,
    estimatedNetSalaryAfter: 43200,
    approverId: 'emp-2',
    approverName: 'Priya Sundaram',
    status: 'rejected',
    appliedDate: '2026-07-12',
    rejectedBy: 'Priya Sundaram',
    rejectedAt: '2026-07-13',
    rejectionReason: 'The requested date overlapped the mandatory production-release coverage window. Please choose 20 July instead.',
  },
  {
    id: 'lr-101',
    employeeId: 'emp-1',
    employeeName: 'Rohan Sharma',
    leaveTypeId: 'lt-1',
    leaveTypeName: 'Casual Leave (CL)',
    isPaid: true,
    startDate: '2026-09-18',
    endDate: '2026-09-18',
    isHalfDay: false,
    reason: 'Family urgent function in Mysore.',
    attachmentName: undefined,
    calendarDays: 1,
    excludedWeekends: 0,
    excludedHolidays: 0,
    chargeableWorkingDays: 1,
    paidDaysUsed: 1,
    unpaidDays: 0,
    estimatedDeduction: 0,
    estimatedNetSalaryAfter: 40750,
    approverId: 'emp-2',
    approverName: 'Priya Sundaram',
    status: 'submitted',
    appliedDate: '2026-09-02',
  },
  {
    id: 'lr-102',
    employeeId: 'emp-1',
    employeeName: 'Rohan Sharma',
    leaveTypeId: 'lt-4',
    leaveTypeName: 'Unpaid Leave (Loss of Pay / LOP)',
    isPaid: false,
    startDate: '2026-08-11',
    endDate: '2026-08-12',
    isHalfDay: false,
    reason: 'Extended leave due to travel delay abroad.',
    attachmentName: 'airline_delay_notice.pdf',
    calendarDays: 2,
    excludedWeekends: 0,
    excludedHolidays: 0,
    chargeableWorkingDays: 2,
    paidDaysUsed: 0,
    unpaidDays: 2,
    estimatedDeduction: 2334,
    estimatedNetSalaryAfter: 38416,
    approverId: 'emp-2',
    approverName: 'Priya Sundaram',
    status: 'approved',
    appliedDate: '2026-08-08',
  },
  {
    id: 'lr-103',
    employeeId: 'emp-1',
    employeeName: 'Rohan Sharma',
    leaveTypeId: 'lt-2',
    leaveTypeName: 'Privilege / Earned Leave (PL/EL)',
    isPaid: true,
    startDate: '2026-06-15',
    endDate: '2026-06-19',
    isHalfDay: false,
    reason: 'Annual family summer vacation.',
    calendarDays: 5,
    excludedWeekends: 0,
    excludedHolidays: 0,
    chargeableWorkingDays: 5,
    paidDaysUsed: 5,
    unpaidDays: 0,
    estimatedDeduction: 0,
    estimatedNetSalaryAfter: 40750,
    approverId: 'emp-2',
    approverName: 'Priya Sundaram',
    status: 'approved',
    appliedDate: '2026-05-20',
  },
  {
    id: 'lr-104',
    employeeId: 'emp-6',
    employeeName: 'Kavita Menon',
    leaveTypeId: 'lt-1',
    leaveTypeName: 'Casual Leave (CL)',
    isPaid: true,
    startDate: '2026-09-22',
    endDate: '2026-09-25',
    isHalfDay: false,
    reason: 'Design conference in Mumbai and travel.',
    calendarDays: 4,
    excludedWeekends: 0,
    excludedHolidays: 0,
    chargeableWorkingDays: 4,
    paidDaysUsed: 4,
    unpaidDays: 0,
    estimatedDeduction: 0,
    estimatedNetSalaryAfter: 52000,
    approverId: 'emp-2',
    approverName: 'Priya Sundaram',
    status: 'submitted',
    appliedDate: '2026-09-03',
  },
  {
    id: 'lr-105',
    employeeId: 'emp-9',
    employeeName: 'Sneha Iyer',
    leaveTypeId: 'lt-3',
    leaveTypeName: 'Sick Leave (SL)',
    isPaid: true,
    startDate: '2026-09-10',
    endDate: '2026-09-11',
    isHalfDay: false,
    reason: 'Viral fever rest advised by doctor.',
    attachmentName: 'medical_prescription.pdf',
    calendarDays: 2,
    excludedWeekends: 0,
    excludedHolidays: 0,
    chargeableWorkingDays: 2,
    paidDaysUsed: 2,
    unpaidDays: 0,
    estimatedDeduction: 0,
    estimatedNetSalaryAfter: 32000,
    approverId: 'emp-2',
    approverName: 'Priya Sundaram',
    status: 'submitted',
    appliedDate: '2026-09-04',
  },
  {
    id: 'lr-106',
    employeeId: 'emp-8',
    employeeName: 'Arjun Verma',
    leaveTypeId: 'lt-2',
    leaveTypeName: 'Privilege / Earned Leave (PL/EL)',
    isPaid: true,
    startDate: '2026-09-04',
    endDate: '2026-09-08',
    isHalfDay: false,
    reason: 'Outstation wedding ceremony.',
    calendarDays: 5,
    excludedWeekends: 2,
    excludedHolidays: 0,
    chargeableWorkingDays: 5,
    normalWorkingDays: 3,
    sandwichDays: 2,
    sandwichPolicyVersion: 1,
    sandwichExplanation: 'Saturday and Sunday are included between approved leave days under company sandwich policy v1.',
    paidDaysUsed: 5,
    unpaidDays: 0,
    estimatedDeduction: 0,
    estimatedNetSalaryAfter: 75000,
    approverId: 'emp-5',
    approverName: 'Sudeesh K',
    status: 'approved',
    appliedDate: '2026-08-25',
  },
  {
    id: 'lr-107',
    employeeId: 'emp-12',
    employeeName: 'Karan Singhania',
    leaveTypeId: 'lt-4',
    leaveTypeName: 'Unpaid Leave (Loss of Pay / LOP)',
    isPaid: false,
    startDate: '2026-09-28',
    endDate: '2026-09-30',
    isHalfDay: false,
    reason: 'Relocation personal commitment beyond probationary balance.',
    calendarDays: 3,
    excludedWeekends: 0,
    excludedHolidays: 0,
    chargeableWorkingDays: 3,
    paidDaysUsed: 0,
    unpaidDays: 3,
    estimatedDeduction: 3400,
    estimatedNetSalaryAfter: 30600,
    approverId: 'emp-4',
    approverName: 'Rajesh Kulkarni',
    status: 'submitted',
    appliedDate: '2026-09-04',
  }
];
