import { LeaveProofPolicy, MedicalProof } from '@/lib/types';

/**
 * Company Leave Proof Policy Configuration.
 * Configurable demonstration policy where medical leave requires supporting proof
 * when chargeable leave duration is 10 days or more.
 */
export const DEMO_LEAVE_PROOF_POLICY: LeaveProofPolicy = {
  leaveTypeId: 'lt-3', // Medical / Sick Leave
  proofRequired: true,
  minimumDurationDays: 10,
  acceptedFileTypes: ['application/pdf', 'image/jpeg', 'image/png'],
  maximumFileSizeMb: 10,
  submissionDeadlineAfterReturnDays: 3,
};

export const INITIAL_MEDICAL_PROOFS: MedicalProof[] = [
  {
    id: 'mp-2026-001',
    leaveRequestId: 'lr-med-101',
    employeeId: 'emp-1',
    employeeName: 'Rohan Sharma',
    department: 'Engineering',
    leaveStartDate: '2026-08-10',
    leaveEndDate: '2026-08-22',
    totalDays: 12,
    expectedReturnDate: '2026-08-24',
    submissionDeadline: '2026-08-27',
    submissionOption: 'with_application',
    fileName: 'Hospital_Admission_Discharge_Summary.pdf',
    fileSizeMb: 2.4,
    fileType: 'application/pdf',
    uploadedAt: '2026-08-09 11:30',
    status: 'verified',
    hrRemarks: 'Verified against Apollo Hospital discharge notes. Authorized.',
    verifiedAt: '2026-08-11 14:15',
    verifiedBy: 'Priya Iyer (HR Manager)',
  },
  {
    id: 'mp-2026-002',
    leaveRequestId: 'lr-med-102',
    employeeId: 'emp-2',
    employeeName: 'Priya Patel',
    department: 'Human Resources',
    leaveStartDate: '2026-09-01',
    leaveEndDate: '2026-09-12',
    totalDays: 11,
    expectedReturnDate: '2026-09-14',
    submissionDeadline: '2026-09-17',
    submissionOption: 'post_return',
    status: 'pending_upload',
    hrRemarks: 'Post-return submission selected. Employee must upload within 3 days of return.',
  },
  {
    id: 'mp-2026-003',
    leaveRequestId: 'lr-med-103',
    employeeId: 'emp-3',
    employeeName: 'Amit Verma',
    department: 'Finance & Accounts',
    leaveStartDate: '2026-08-18',
    leaveEndDate: '2026-08-30',
    totalDays: 13,
    expectedReturnDate: '2026-09-01',
    submissionDeadline: '2026-09-04',
    submissionOption: 'with_application',
    fileName: 'Physician_Certificate_DrMehta.jpg',
    fileSizeMb: 3.8,
    fileType: 'image/jpeg',
    uploadedAt: '2026-08-17 09:12',
    status: 'under_hr_review',
    hrRemarks: 'Pending clinic stamp and physician license verification.',
  },
  {
    id: 'mp-2026-004',
    leaveRequestId: 'lr-med-104',
    employeeId: 'emp-4',
    employeeName: 'Sneha Kulkarni',
    department: 'Product Design',
    leaveStartDate: '2026-08-01',
    leaveEndDate: '2026-08-14',
    totalDays: 14,
    expectedReturnDate: '2026-08-16',
    submissionDeadline: '2026-08-19',
    submissionOption: 'with_application',
    fileName: 'prescription_scan.png',
    fileSizeMb: 1.2,
    fileType: 'image/png',
    uploadedAt: '2026-08-01 16:45',
    status: 'resubmission_required',
    hrRemarks: 'Prescription slip is blurred and diagnosis date is truncated. Please upload a clear hospital letter.',
  },
  {
    id: 'mp-2026-005',
    leaveRequestId: 'lr-med-105',
    employeeId: 'emp-5',
    employeeName: 'Vikram Rao',
    department: 'Operations & Logistics',
    leaveStartDate: '2026-07-20',
    leaveEndDate: '2026-08-02',
    totalDays: 14,
    expectedReturnDate: '2026-08-04',
    submissionDeadline: '2026-08-07',
    submissionOption: 'post_return',
    status: 'overdue',
    hrRemarks: 'Return date passed and deadline expired on 07 Aug. Auto-escalated to HR Manager.',
  },
];
