import { SalaryRule, SalaryStructure, Payrun, Payslip, PayrollWarning } from '@/lib/types';

export const SALARY_RULES: SalaryRule[] = [
  {
    id: 'rule-1',
    name: 'Basic Salary',
    code: 'BASIC',
    category: 'basic',
    sequence: 1,
    calculationType: 'fixed',
    fixedAmount: 35000,
    isActive: true,
    description: 'Primary taxable wage component fixed by employment contract.',
  },
  {
    id: 'rule-2',
    name: 'House Rent Allowance (HRA)',
    code: 'HRA',
    category: 'allowance',
    sequence: 2,
    calculationType: 'percentage',
    percentage: 40,
    formulaDisplay: '40% of BASIC',
    condition: 'Applicable to metro residency',
    isActive: true,
    description: 'Statutory accommodation allowance under Section 10(13A).',
  },
  {
    id: 'rule-3',
    name: 'Travel Allowance',
    code: 'TRAV',
    category: 'allowance',
    sequence: 3,
    calculationType: 'fixed',
    fixedAmount: 3500,
    isActive: true,
    description: 'Standard conveyance subsidy for office commute.',
  },
  {
    id: 'rule-4',
    name: 'Special Allowance',
    code: 'SPEC',
    category: 'allowance',
    sequence: 4,
    calculationType: 'fixed',
    fixedAmount: 5000,
    isActive: true,
    description: 'Flexible balancing allowance component in cost-to-company.',
  },
  {
    id: 'rule-5',
    name: 'Overtime Compensation',
    code: 'OT',
    category: 'allowance',
    sequence: 5,
    calculationType: 'formula',
    formulaDisplay: '(BASIC / 160) * 1.5 * OT_HOURS',
    condition: 'Requires supervisor approved biometric log',
    isActive: true,
    description: 'Time-and-a-half compensation for approved extra working hours.',
  },
  {
    id: 'rule-6',
    name: 'Provident Fund (Employee PF)',
    code: 'PF_EMP',
    category: 'deduction',
    sequence: 6,
    calculationType: 'fixed',
    fixedAmount: 1800,
    formulaDisplay: 'Min(12% of BASIC, 1800)',
    isActive: true,
    description: 'Statutory employee retirement savings contribution under EPF Act.',
  },
  {
    id: 'rule-7',
    name: 'Professional Tax (PT)',
    code: 'PT',
    category: 'deduction',
    sequence: 7,
    calculationType: 'fixed',
    fixedAmount: 200,
    isActive: true,
    description: 'State statutory professional tax levy (Karnataka slab).',
  },
  {
    id: 'rule-8',
    name: 'Tax Deducted at Source (TDS)',
    code: 'TDS',
    category: 'deduction',
    sequence: 8,
    calculationType: 'fixed',
    fixedAmount: 750,
    isActive: true,
    description: 'Estimated monthly income tax withholding per new tax regime.',
  },
  {
    id: 'rule-9',
    name: 'Unpaid Leave (Loss of Pay / LOP)',
    code: 'LOP_DED',
    category: 'deduction',
    sequence: 9,
    calculationType: 'formula',
    formulaDisplay: '(Gross_Salary / Working_Days) * Unpaid_Days',
    condition: 'Triggered by unapproved absence or exhausted paid balance',
    isActive: true,
    description: 'Salary reduction for unpaid leave or unauthorized absence.',
  },
];

export const SALARY_STRUCTURES: SalaryStructure[] = [
  {
    id: 'str-1',
    name: 'Standard Corporate Salary Structure',
    code: 'CORP-STD-2026',
    isActive: true,
    assignedEmployeesCount: 68,
    ruleIds: ['rule-1', 'rule-2', 'rule-3', 'rule-4', 'rule-6', 'rule-7', 'rule-8', 'rule-9'],
  },
  {
    id: 'str-2',
    name: 'Tech Engineering Salary Structure',
    code: 'TECH-ENG-2026',
    isActive: true,
    assignedEmployeesCount: 42,
    ruleIds: ['rule-1', 'rule-2', 'rule-3', 'rule-4', 'rule-5', 'rule-6', 'rule-7', 'rule-8', 'rule-9'],
  },
  {
    id: 'str-3',
    name: 'Executive Leadership Salary Structure',
    code: 'EXEC-DIR-2026',
    isActive: true,
    assignedEmployeesCount: 8,
    ruleIds: ['rule-1', 'rule-2', 'rule-4', 'rule-6', 'rule-7', 'rule-8'],
  },
];

export const PAYROLL_WARNINGS: PayrollWarning[] = [
  {
    id: 'warn-1',
    employeeId: 'emp-11',
    employeeName: 'Meera Nambiar',
    type: 'missing_bank_details',
    severity: 'blocking',
    message: 'Missing IFSC and bank account number for direct salary disbursement.',
  },
  {
    id: 'warn-2',
    employeeId: 'emp-7',
    employeeName: 'Aarav Mukherjee',
    type: 'attendance_exception',
    severity: 'warning',
    message: 'Unverified absence on Sep 04. Requires supervisor regularization before computation.',
  },
  {
    id: 'warn-3',
    employeeId: 'emp-9',
    employeeName: 'Sneha Iyer',
    type: 'attendance_exception',
    severity: 'warning',
    message: 'Late arrival exception pending manager review.',
  },
  {
    id: 'warn-4',
    employeeId: 'emp-1',
    employeeName: 'Rohan Sharma',
    type: 'leave_conflict',
    severity: 'warning',
    message: 'Pending leave request overlaps with payrun settlement cutoff.',
  },
];

export const INITIAL_PAYRUNS: Payrun[] = [
  {
    id: 'pr-202608',
    name: 'Regular Payrun - August 2026',
    reference: 'PAYRUN-2026-08-REG',
    salaryStructureId: 'str-2',
    salaryStructureName: 'Tech Engineering Salary Structure',
    startDate: '2026-08-01',
    endDate: '2026-08-31',
    departmentName: 'All Departments',
    employeeType: 'Full-Time Employees',
    status: 'paid',
    employeeCount: 12,
    grossTotal: 732500,
    totalDeductions: 48900,
    netTotal: 683600,
    warningCount: 0,
    readinessScore: 100,
    createdAt: '2026-08-25',
    computedAt: '2026-08-27 11:30 AM',
    validatedAt: '2026-08-29 03:15 PM',
    paidAt: '2026-08-31 09:00 AM',
  },
  {
    id: 'pr-202609',
    name: 'Regular Payrun - September 2026',
    reference: 'PAYRUN-2026-09-REG',
    salaryStructureId: 'str-2',
    salaryStructureName: 'Tech Engineering Salary Structure',
    startDate: '2026-09-01',
    endDate: '2026-09-30',
    departmentName: 'All Departments',
    employeeType: 'Full-Time Employees',
    status: 'computed',
    employeeCount: 12,
    grossTotal: 748000,
    totalDeductions: 51200,
    netTotal: 696800,
    warningCount: 4,
    readinessScore: 88,
    createdAt: '2026-09-01',
    computedAt: '2026-09-04 10:45 AM',
  },
  {
    id: 'pr-202610',
    name: 'Regular Payrun - October 2026',
    reference: 'PAYRUN-2026-10-REG',
    salaryStructureId: 'str-1',
    salaryStructureName: 'Standard Corporate Salary Structure',
    startDate: '2026-10-01',
    endDate: '2026-10-31',
    departmentName: 'All Departments',
    employeeType: 'Full-Time Employees',
    status: 'draft',
    employeeCount: 12,
    grossTotal: 748000,
    totalDeductions: 50400,
    netTotal: 697600,
    warningCount: 2,
    readinessScore: 72,
    createdAt: '2026-09-04',
  },
];

export const INITIAL_PAYSLIPS: Payslip[] = [
  {
    id: 'ps-202608-emp1',
    payrunId: 'pr-202608',
    payrunName: 'Regular Payrun - August 2026',
    employeeId: 'emp-1',
    employeeName: 'Rohan Sharma',
    employeeCode: 'PP-EMP-1042',
    department: 'Engineering',
    jobPosition: 'Senior Software Engineer',
    contractId: 'cnt-1',
    salaryStructureId: 'str-2',
    salaryStructureName: 'Tech Engineering Salary Structure',
    payrollPeriod: '01 Aug 2026 - 31 Aug 2026',
    workedDays: 20,
    paidLeaveDays: 0,
    unpaidLeaveDays: 2,
    basicSalary: 35000,
    hra: 5000,
    travelAllowance: 2000,
    otherAllowances: 1500,
    grossSalary: 44250,
    bonus: 0,
    appraisalAdjustment: 0,
    overtime: 750,
    paidLeaveAdjustment: 0,
    unpaidLeaveDeduction: 2334,
    taxDeduction: 750,
    otherDeductions: 2000, // PF + PT
    totalDeductions: 5084,
    netSalary: 39166,
    status: 'paid',
    warnings: [],
    previousNetSalary: 43200,
    difference: -2450,
    percentageChange: -5.67,
    changeReason: 'Net salary decreased by ₹2,450 because of two unpaid leave days, partially offset by approved overtime hours.',
    lines: [
      {
        id: 'line-1',
        name: 'Basic Salary',
        code: 'BASIC',
        category: 'basic',
        amount: 35000,
        source: 'contract',
        explanation: 'Agreed contractual monthly base pay under CNT-2024-ENG-042.',
      },
      {
        id: 'line-2',
        name: 'House Rent Allowance (HRA)',
        code: 'HRA',
        category: 'allowance',
        amount: 5000,
        source: 'salary_rule',
        explanation: 'Statutory housing support component.',
      },
      {
        id: 'line-3',
        name: 'Travel Allowance',
        code: 'TRAV',
        category: 'allowance',
        amount: 2000,
        source: 'salary_rule',
        explanation: 'Monthly conveyance allowance for office commute.',
      },
      {
        id: 'line-4',
        name: 'Special Allowance',
        code: 'SPEC',
        category: 'allowance',
        amount: 1500,
        source: 'salary_rule',
        explanation: 'Balancing allowance under compensation structure.',
      },
      {
        id: 'line-5',
        name: 'Overtime Compensation',
        code: 'OT',
        category: 'overtime',
        amount: 750,
        source: 'overtime',
        hoursAffected: 2.3,
        explanation: '2.3 hours approved biometric overtime logged on Aug 28 & Sep 02.',
      },
      {
        id: 'line-6',
        name: 'Provident Fund (EPF)',
        code: 'PF_EMP',
        category: 'deduction',
        amount: 1800,
        source: 'salary_rule',
        explanation: 'Statutory employee retirement deduction credited to EPFO UAN account.',
      },
      {
        id: 'line-7',
        name: 'Professional Tax (Karnataka)',
        code: 'PT',
        category: 'deduction',
        amount: 200,
        source: 'salary_rule',
        explanation: 'State professional tax deduction.',
      },
      {
        id: 'line-8',
        name: 'TDS (Income Tax)',
        code: 'TDS',
        category: 'tax',
        amount: 750,
        source: 'salary_rule',
        explanation: 'Monthly tax withholding deposited to ITD.',
      },
    ],
  },
  {
    id: 'ps-202608-emp2',
    payrunId: 'pr-202608',
    payrunName: 'Regular Payrun - August 2026',
    employeeId: 'emp-2',
    employeeName: 'Priya Sundaram',
    employeeCode: 'PP-HR-2008',
    department: 'Human Resources',
    jobPosition: 'People Operations Manager',
    contractId: 'cnt-2',
    salaryStructureId: 'str-1',
    salaryStructureName: 'Standard Corporate Salary Structure',
    payrollPeriod: '01 Aug 2026 - 31 Aug 2026',
    workedDays: 22,
    paidLeaveDays: 0,
    unpaidLeaveDays: 0,
    basicSalary: 45000,
    hra: 18000,
    travelAllowance: 4000,
    otherAllowances: 8000,
    grossSalary: 75000,
    bonus: 0,
    appraisalAdjustment: 0,
    overtime: 0,
    paidLeaveAdjustment: 0,
    unpaidLeaveDeduction: 0,
    taxDeduction: 4500,
    otherDeductions: 2000,
    totalDeductions: 6500,
    netSalary: 68500,
    status: 'paid',
    warnings: [],
    previousNetSalary: 68500,
    difference: 0,
    percentageChange: 0,
    lines: [
      { id: 'l2-1', name: 'Basic Salary', code: 'BASIC', category: 'basic', amount: 45000, source: 'contract' },
      { id: 'l2-2', name: 'HRA', code: 'HRA', category: 'allowance', amount: 18000, source: 'salary_rule' },
      { id: 'l2-3', name: 'Travel Allowance', code: 'TRAV', category: 'allowance', amount: 4000, source: 'salary_rule' },
      { id: 'l2-4', name: 'Special Allowance', code: 'SPEC', category: 'allowance', amount: 8000, source: 'salary_rule' },
      { id: 'l2-5', name: 'EPF', code: 'PF_EMP', category: 'deduction', amount: 1800, source: 'salary_rule' },
      { id: 'l2-6', name: 'PT', code: 'PT', category: 'deduction', amount: 200, source: 'salary_rule' },
      { id: 'l2-7', name: 'TDS', code: 'TDS', category: 'tax', amount: 4500, source: 'salary_rule' },
    ],
  },
];

const monthlyPeriods = Array.from({ length: 12 }, (_, index) => {
  const month = String(index + 1).padStart(2, '0');
  const lastDay = new Date(Date.UTC(2026, index + 1, 0)).getUTCDate();
  const monthLabel = new Date(Date.UTC(2026, index, 1)).toLocaleString('en-US', { month: 'long' });
  return { month, lastDay, monthLabel };
});

const monthlySamples = INITIAL_PAYSLIPS.flatMap((sample) => monthlyPeriods
  .filter((period) => !sample.id.includes(`2026${period.month}`))
  .map((period) => {
    const grossSalary = sample.grossSalary;
    const deductions = sample.totalDeductions;
    return {
      ...sample,
      id: `${sample.id.slice(0, -6)}2026${period.month}`,
      payrunId: `pr-2026${period.month}`,
      payrunName: `Regular Payrun - ${period.monthLabel} 2026`,
      payrollPeriod: `01 ${period.monthLabel.slice(0, 3)} 2026 - ${period.lastDay} ${period.monthLabel.slice(0, 3)} 2026`,
      period: `${period.monthLabel} 2026`,
      grossSalary,
      netSalary: grossSalary - deductions,
      lines: sample.lines.map((line) => ({ ...line, id: `${line.id}-2026${period.month}` })),
    };
  }));

export const ALL_INITIAL_PAYSLIPS: Payslip[] = [...INITIAL_PAYSLIPS, ...monthlySamples];
