import { User } from '@/lib/types';

export const DEMO_USERS: User[] = [
  {
    id: 'usr-1',
    name: 'Rohan Sharma',
    email: 'rohan.sharma@peoplepay360.internal',
    role: 'employee',
    roleTitle: 'Employee',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    employeeId: 'PP-EMP-1042',
    department: 'Engineering',
    jobPosition: 'Senior Software Engineer',
  },
  {
    id: 'usr-2',
    name: 'Priya Sundaram',
    email: 'priya.sundaram@peoplepay360.internal',
    role: 'hr_manager',
    roleTitle: 'HR Manager',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    employeeId: 'PP-HR-2008',
    department: 'Human Resources',
    jobPosition: 'People Operations Manager',
  },
  {
    id: 'usr-3',
    name: 'Neha Gupta',
    email: 'neha.gupta@peoplepay360.internal',
    role: 'payroll_user',
    roleTitle: 'HR Payroll User',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    employeeId: 'PP-PAY-3015',
    department: 'Finance & Payroll',
    jobPosition: 'Payroll Specialist',
  },
  {
    id: 'usr-4',
    name: 'Rajesh Kulkarni',
    email: 'rajesh.kulkarni@peoplepay360.internal',
    role: 'payroll_manager',
    roleTitle: 'HR Payroll Manager',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    employeeId: 'PP-PAY-3001',
    department: 'Finance & Payroll',
    jobPosition: 'Payroll Operations Director',
  },
  {
    id: 'usr-5',
    name: 'Sudeesh K',
    email: 'sudeesh.k@peoplepay360.internal',
    role: 'admin',
    roleTitle: 'Admin',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    employeeId: 'PP-ADM-1001',
    department: 'Executive Administration',
    jobPosition: 'Global HR Operations Administrator',
  },
];
