import { NextRequest,NextResponse } from 'next/server';
import { generateAuthenticationOptions,verifyAuthenticationResponse } from '@simplewebauthn/server';
import type { AuthenticationResponseJSON } from '@simplewebauthn/server';
import { z } from 'zod';
import { createServiceRoleClient,createUserScopedClient } from '@/lib/supabase/server';
const schema=z.object({challengeId:z.string().uuid(),response:z.custom<AuthenticationResponseJSON>()});
async function ctx(request:NextRequest){const token=request.headers.get('authorization')?.replace(/^Bearer\s+/,'');if(!token)throw new Error('Authentication required');const scoped=createUserScopedClient(token),service=createServiceRoleClient();const {data:auth}=await scoped.auth.getUser(token);if(!auth.user)throw new Error('Authentication required');const {data:employee}=await service.from('employees').select('*').eq('user_id',auth.user.id).single();if(!employee)throw new Error('Employee not found');return {service,user:auth.user,employee}}
export async function GET(request:NextRequest){try{const {service,user}=await ctx(request);const {data:credentials}=await service.from('employee_webauthn_credentials').select('*').eq('user_id',user.id).is('revoked_at',null);if(!credentials?.length)return NextResponse.json({error:{message:'Laptop biometric is not enrolled'}},{status:409});const options=await generateAuthenticationOptions({rpID:process.env.WEBAUTHN_RP_ID||request.nextUrl.hostname,userVerification:'required',allowCredentials:credentials.map(item=>({id:item.credential_id,transports:item.transports}))});const {data:challenge,error}=await service.from('webauthn_challenges').insert({user_id:user.id,purpose:'authentication',challenge:options.challenge,expires_at:new Date(Date.now()+300000).toISOString()}).select().single();if(error||!challenge)throw error||new Error('Unable to save challenge');return NextResponse.json({challengeId:challenge.id,options});}catch(error){return NextResponse.json({error:{message:error instanceof Error?error.message:'Unable to start verification'}},{status:400})}}
export async function POST(request:NextRequest){try{const {service,user,employee}=await ctx(request);const input=schema.parse(await request.json());const [{data:challenge},{data:credential}]=await Promise.all([service.from('webauthn_challenges').select('*').eq('id',input.challengeId).eq('user_id',user.id).eq('purpose','authentication').is('consumed_at',null).gt('expires_at',new Date().toISOString()).single(),service.from('employee_webauthn_credentials').select('*').eq('credential_id',input.response.id).eq('user_id',user.id).is('revoked_at',null).single()]);if(!challenge||!credential)return NextResponse.json({error:{message:'Credential or challenge is invalid'}},{status:409});const verification=await verifyAuthenticationResponse({response:input.response,expectedChallenge:challenge.challenge,expectedOrigin:process.env.WEBAUTHN_ORIGIN||request.nextUrl.origin,expectedRPID:process.env.WEBAUTHN_RP_ID||request.nextUrl.hostname,credential:{id:credential.credential_id,publicKey:Buffer.from(credential.public_key,'base64url'),counter:credential.counter,transports:credential.transports},requireUserVerification:true});if(!verification.verified)throw new Error('Laptop biometric verification failed');await Promise.all([service.from('employee_webauthn_credentials').update({counter:verification.authenticationInfo.newCounter,last_used_at:new Date().toISOString()}).eq('id',credential.id),service.from('webauthn_challenges').update({consumed_at:new Date().toISOString()}).eq('id',challenge.id),service.from('biometric_verification_events').insert({company_id:employee.company_id,employee_id:employee.id,method:'webauthn',outcome:'verified',liveness_passed:null,credential_id:credential.credential_id,metadata:{}})]);return NextResponse.json({verified:true});}catch(error){return NextResponse.json({error:{message:error instanceof Error?error.message:'Biometric verification failed'}},{status:400})}}
