import { jsPDF } from 'jspdf';

export type ExportCell = string | number | boolean | null | undefined;

function saveBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  anchor.style.display = 'none';
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function csvCell(value: ExportCell) {
  return `"${String(value ?? '').replaceAll('"', '""')}"`;
}

export function downloadCsv(filename: string, headers: string[], rows: ExportCell[][]) {
  const csv = [headers, ...rows].map((row) => row.map(csvCell).join(',')).join('\r\n');
  saveBlob(new Blob([`\uFEFF${csv}`], { type: 'text/csv;charset=utf-8' }), filename);
}

export function downloadText(filename: string, content: string) {
  saveBlob(new Blob([content], { type: 'text/plain;charset=utf-8' }), filename);
}

export function downloadReportPdf(input: {
  filename: string;
  title: string;
  subtitle: string;
  headers: string[];
  rows: ExportCell[][];
  summary?: string[];
}) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 14;
  let y = 16;
  doc.setFillColor(113, 75, 103);
  doc.rect(0, 0, pageWidth, 8, 'F');
  doc.setTextColor(40, 38, 45);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text(input.title, margin, y);
  y += 6;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(116, 113, 122);
  doc.text(input.subtitle, margin, y);
  y += 8;
  if (input.summary) {
    input.summary.forEach((line) => { doc.text(line, margin, y); y += 5; });
    y += 2;
  }
  const columnWidth = (pageWidth - margin * 2) / input.headers.length;
  const drawHeader = () => {
    doc.setFillColor(244, 243, 245);
    doc.rect(margin, y - 4, pageWidth - margin * 2, 7, 'F');
    doc.setTextColor(77, 51, 72);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7);
    input.headers.forEach((header, index) => doc.text(header.slice(0, 24), margin + index * columnWidth + 1, y));
    y += 6;
  };
  drawHeader();
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(40, 38, 45);
  input.rows.forEach((row) => {
    if (y > 280) { doc.addPage(); y = 16; drawHeader(); }
    row.forEach((cell, index) => doc.text(String(cell ?? '').slice(0, 28), margin + index * columnWidth + 1, y));
    doc.setDrawColor(228, 225, 229);
    doc.line(margin, y + 2, pageWidth - margin, y + 2);
    y += 6;
  });
  doc.setFontSize(7);
  doc.setTextColor(116, 113, 122);
  doc.text(`Generated by PeoplePay360 on ${new Date().toLocaleString('en-IN')}`, margin, 291);
  doc.save(input.filename);
}
